name: Check for Good First Issues

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Check for new issues
      id: check_issues
      run: |
        current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        ten_minutes_ago=$(date -u -d "-10 minutes" +"%Y-%m-%dT%H:%M:%SZ")
        curl -s https://api.github.com/repos/paradigmxyz/reth/issues | jq -r --arg current_time "$current_time" --arg ten_minutes_ago "$ten_minutes_ago" '.[] | select(.labels[].name == "D-good-first-issue" and .created_at >= $ten_minutes_ago and .created_at < $current_time) | .html_url' > issues.txt
        if [ -s issues.txt ]; then
          echo "new_issues=true" >> $GITHUB_ENV
        else
          echo "new_issues=false" >> $GITHUB_ENV
        fi

    - name: Send Telegram Notification
      if: env.new_issues == 'true'
      run: |
        while IFS= read -r issue; do
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="New Good First Issue: $issue"
        done < issues.txt
